#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#include <cstdlib>
#include <iostream>
#include <sstream>
#include <string>

//Boyels law
Fl_Input* Pv1;
Fl_Input* Pv2;
Fl_Input* Vi1;
Fl_Input* vi2;
Fl_Output* P1aR;
Fl_Output* P2aR;
Fl_Output* V1aR;
Fl_Output* V2aR;

//Ideal Gass Law
Fl_Input* idgP1;
Fl_Input* idgP2;
Fl_Input* idgT1;
Fl_Input* idgT2;
Fl_Input* idgV1;
Fl_Input* idgV2;
Fl_Input* Gc;
Fl_Input* m;
Fl_Output* idgaRP1;
Fl_Output* idgaRP2;
Fl_Output* idgaRT1;
Fl_Output* idgaRT2;
Fl_Output* idgaRV1;
Fl_Output* idgaRV2;
//Elastic Equaison
Fl_Input* m1Input;
Fl_Input* m2Input;
Fl_Input* v1Input;
Fl_Input* v2Input;
Fl_Output* v1Output;
Fl_Output* v2Output;
//ohms law
Fl_Input* P;
Fl_Input* E;
Fl_Input* R;
Fl_Input* I;
Fl_Output* PaR;
Fl_Output* PaR1;
Fl_Output* PaR2;
Fl_Output* EaR;
Fl_Output* EaR1;
Fl_Output* EaR2;
Fl_Output* RaR;
Fl_Output* RaR1;
Fl_Output* RaR2;
Fl_Output* IaR;
Fl_Output* IaR1;
Fl_Output* IaR2;

